name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: build
        run: zig build
      
      - name: run cppfront
        run: zig build cppfront

      - name: run C++ example
        run: zig build hello_cpp
