name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - name: Build
        run: zig build --summary all
      
      - name: build and run cppfront
        run: zig build cppfront

      - name: run C++ example
        run: zig build run
