name: CI

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: mlugg/setup-zig@v2
        with:
          version: master

      - name: Build
        run: zig build --summary all
      
      - name: cppfront - cpp2 to cpp1
        run: |
          zig build cppfront -Dpure
          zig build cppfront -Dpure -Dcpp2="examples/pure2-enum.cpp2"
          zig build cppfront -Dpure -Dcpp2="examples/pure2-forward-return.cpp2"
          # zig build cppfront -Dcpp2="examples/mixed-bounds-check.cpp2"
      - name: Run
        run: |
          zig build run -Dpure
          zig build run -Dpure -Dcpp2="examples/pure2-enum.cpp2"
          zig build run -Dpure -Dcpp2="examples/pure2-forward-return.cpp2"
          # zig build run -Dcpp2="examples/mixed-bounds-check.cpp2"
